source 'https://github.com/CocoaPods/Specs.git'

target 'FilmAPI', :exclusive => true do
  pod 'hpple'
  pod 'AFNetworking'
  pod 'DzCategory'
  pod 'XMLDictionary'
  pod 'FCFileManager'
end

target 'Tests', :exclusive => true do
end
